### ISSUE TITLE
Excessively long words can make vote comment overflow box

### ISSUE THREAD

**Issue by Yirba** [very-scary-scenario/nkd.su#109]
A real example (see Ben's vote for _My story ~Mada Minu Ashita he~_ [here](http://nkd.su/show/2014-05-17/)) of such a vote is "FOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOTTTTTTTTBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLLLLL".

I thought about different solutions to this, but this is the one I'd go with:

``` css
.text {
    word-wrap: break-word;
    overflow: hidden; /* fallback for inferior browsers lacking word-wrap capabilities */
}
```

Might possibly want to make the selector a bit more specific, but this should break up excessively long words.
